// <auto-generated />
using System;
using IyilikCatisi.Data.Concrete.EntityFramework.context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IyilikCatisi.Data.Migrations
{
    [DbContext(typeof(İyilikCatisiDbContext))]
    [Migration("20250107162942_baslangic")]
    partial class baslangic
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IyilikCatisi.Model.Entity.Bagislar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("Aktif")
                        .HasColumnType("bit");

                    b.Property<decimal>("BagisMiktari")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime>("BagisTarihi")
                        .HasColumnType("datetime");

                    b.Property<int?>("BagisTuru")
                        .HasColumnType("int");

                    b.Property<string>("BagislaIlgiliMesaj")
                        .HasColumnType("text");

                    b.Property<int?>("DegistirenId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DegistirilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int?>("OlusturanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soyadi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TcKimlikNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Bagislar", (string)null);
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.BildirimKullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int>("BildirimId")
                        .HasColumnType("int");

                    b.Property<int?>("DegistirenId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DegistirilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int?>("OlusturanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BildirimId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("BildirimKullanici", (string)null);
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.Bildirimler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("BildirimBasligi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BildirimIcerigi")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("BildirimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DegistirenId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DegistirilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<int?>("OlusturanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OlusturanId");

                    b.ToTable("Bildirimler", (string)null);
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.Etkinlik", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Baslik")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DegistirenId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DegistirilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Konum")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("OlusturanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly?>("Saat")
                        .HasColumnType("time");

                    b.Property<DateOnly?>("Tarih")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("OlusturanId");

                    b.ToTable("Etkinlik", (string)null);
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.EtkinlikFotograflari", b =>
                {
                    b.Property<int>("EtkinlikId")
                        .HasColumnType("int");

                    b.Property<bool?>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int?>("DegistirenId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DegistirilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fotograf")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FotografAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("OlusturanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("EtkinlikId");

                    b.ToTable("EtkinlikFotograflari", (string)null);
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.Haberler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("DegistirenId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DegistirilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Etiketler")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("GoruntulenmeSayisi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OlusturanId")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("YayinTarihi")
                        .HasColumnType("date");

                    b.Property<string>("Yazar")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Haberler__3214EC077EB4FA16");

                    b.HasIndex("OlusturanKullaniciId");

                    b.ToTable("Haberler", (string)null);
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.KullaniciRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int?>("DegistirenId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DegistirilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int?>("OlusturanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("RolId");

                    b.ToTable("KullaniciRol", (string)null);
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.Kullanicilar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Adres")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("CepTel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<bool?>("CepTelOnay")
                        .HasColumnType("bit");

                    b.Property<int?>("DegistirenId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DegistirilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DogumTarihi")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("EpostaOnay")
                        .HasColumnType("bit");

                    b.Property<int?>("HataliGirisSayisi")
                        .HasColumnType("int");

                    b.Property<int?>("OlusturanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Soyadi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TcKimlikNo")
                        .HasColumnType("int");

                    b.Property<Guid?>("UniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("UyelikDurumuId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UyelikTarihi")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("UyelikDurumuId");

                    b.ToTable("Kullanicilar", (string)null);
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.Makaleler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("AnahtarKelime")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("DegistirenId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DegistirilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GoruntulenmeSayisi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OlusturanId")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("YayinTarihi")
                        .HasColumnType("date");

                    b.Property<string>("Yazar")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Makalele__3214EC07E8AA2610");

                    b.HasIndex("OlusturanKullaniciId");

                    b.ToTable("Makaleler", (string)null);
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Baslik")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DegistirenId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DegistirilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MenuIcon")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("OlusturanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UstMenuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UstMenuId");

                    b.ToTable("Menu", (string)null);
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.MenuYetki", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int?>("DegistirenId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DegistirilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("DeleteYetki")
                        .HasColumnType("bit");

                    b.Property<bool?>("InsertYetki")
                        .HasColumnType("bit");

                    b.Property<int?>("MenuId")
                        .HasColumnType("int");

                    b.Property<int?>("OlusturanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RolId")
                        .HasColumnType("int");

                    b.Property<bool?>("SelectYetki")
                        .HasColumnType("bit");

                    b.Property<bool?>("UpdateYetki")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("RolId");

                    b.ToTable("MenuYetki", (string)null);
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.MesajTip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int?>("DegistirenId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DegistirilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MesajTipi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("OlusturanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MesajTip", (string)null);
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.Mesajlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int?>("DegistirenId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DegistirilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("MesajIcerigi")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("MesajTipId")
                        .HasColumnType("int");

                    b.Property<int?>("OlusturanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("MesajTipId");

                    b.ToTable("Mesajlar", (string)null);
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.Roller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int?>("DegistirenId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DegistirilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OlusturanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("RolAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roller", (string)null);
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.UyelikAidatlari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AidatOdemePeriyodu")
                        .HasColumnType("int");

                    b.Property<decimal?>("AidatTutari")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<bool?>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int?>("DegistirenId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DegistirilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("KayitTarihi")
                        .HasColumnType("date");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("OdemeSonTarihi")
                        .HasColumnType("date");

                    b.Property<int?>("OlusturanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("UyelikAidatlari", (string)null);
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.UyelikDurumu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int?>("DegistirenId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DegistirilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OlusturanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("UyelikDurumu1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("UyelikDurumu");

                    b.HasKey("Id");

                    b.ToTable("UyelikDurumu", (string)null);
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.YetkiRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int?>("DegistirenId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DegistirilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OlusturanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("YetkiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("YetkiId");

                    b.ToTable("YetkiRol", (string)null);
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.Yetkiler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int?>("DegistirenId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DegistirilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OlusturanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("YetkiAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Yetkiler", (string)null);
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.YorumTip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int?>("DegistirenId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DegistirilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OlusturanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("YorumTipi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("YorumTip", (string)null);
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.Yorumlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int?>("DegistirenId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DegistirilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int?>("OlusturanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("YorumMetni")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("YorumTipId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("YorumTipId");

                    b.ToTable("Yorumlar", (string)null);
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.Bagislar", b =>
                {
                    b.HasOne("IyilikCatisi.Model.Entity.Kullanicilar", "Kullanici")
                        .WithMany("Bagislars")
                        .HasForeignKey("KullaniciId")
                        .HasConstraintName("FK_Bagislar_Kullanicilar");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.BildirimKullanici", b =>
                {
                    b.HasOne("IyilikCatisi.Model.Entity.Bildirimler", "Bildirim")
                        .WithMany("BildirimKullanicis")
                        .HasForeignKey("BildirimId")
                        .IsRequired()
                        .HasConstraintName("FK_BildirimKullanici_Bildirimler");

                    b.HasOne("IyilikCatisi.Model.Entity.Kullanicilar", "Kullanici")
                        .WithMany("BildirimKullanicis")
                        .HasForeignKey("KullaniciId")
                        .IsRequired()
                        .HasConstraintName("FK_BildirimKullanici_Kullanicilar");

                    b.Navigation("Bildirim");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.Bildirimler", b =>
                {
                    b.HasOne("IyilikCatisi.Model.Entity.Kullanicilar", "OlusturanKullanici")
                        .WithMany("Bildirimlers")
                        .HasForeignKey("OlusturanId")
                        .HasConstraintName("FK_Bildirimler_Kullanicilar");

                    b.Navigation("OlusturanKullanici");
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.Etkinlik", b =>
                {
                    b.HasOne("IyilikCatisi.Model.Entity.Kullanicilar", "Olusturan")
                        .WithMany("Etkinliks")
                        .HasForeignKey("OlusturanId");

                    b.Navigation("Olusturan");
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.EtkinlikFotograflari", b =>
                {
                    b.HasOne("IyilikCatisi.Model.Entity.Etkinlik", "Etkinlik")
                        .WithOne("EtkinlikFotograflari")
                        .HasForeignKey("IyilikCatisi.Model.Entity.EtkinlikFotograflari", "EtkinlikId")
                        .IsRequired()
                        .HasConstraintName("FK_EtkinlikFotograflari_Etkinlik");

                    b.Navigation("Etkinlik");
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.Haberler", b =>
                {
                    b.HasOne("IyilikCatisi.Model.Entity.Kullanicilar", "OlusturanKullanici")
                        .WithMany("Haberlers")
                        .HasForeignKey("OlusturanKullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OlusturanKullanici");
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.KullaniciRol", b =>
                {
                    b.HasOne("IyilikCatisi.Model.Entity.Kullanicilar", "Kullanici")
                        .WithMany("KullaniciRols")
                        .HasForeignKey("KullaniciId")
                        .IsRequired()
                        .HasConstraintName("FK_KullaniciRol_Kullanicilar");

                    b.HasOne("IyilikCatisi.Model.Entity.Roller", "Rol")
                        .WithMany("KullaniciRols")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK_KullaniciRol_Roller");

                    b.Navigation("Kullanici");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.Kullanicilar", b =>
                {
                    b.HasOne("IyilikCatisi.Model.Entity.UyelikDurumu", "UyelikDurumu")
                        .WithMany("Kullanicilars")
                        .HasForeignKey("UyelikDurumuId")
                        .HasConstraintName("FK_Kullanicilar_UyelikDurumu");

                    b.Navigation("UyelikDurumu");
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.Makaleler", b =>
                {
                    b.HasOne("IyilikCatisi.Model.Entity.Kullanicilar", "OlusturanKullanici")
                        .WithMany("Makalelers")
                        .HasForeignKey("OlusturanKullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OlusturanKullanici");
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.Menu", b =>
                {
                    b.HasOne("IyilikCatisi.Model.Entity.Menu", "UstMenu")
                        .WithMany("InverseUstMenu")
                        .HasForeignKey("UstMenuId")
                        .HasConstraintName("FK_Menu_Menu");

                    b.Navigation("UstMenu");
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.MenuYetki", b =>
                {
                    b.HasOne("IyilikCatisi.Model.Entity.Menu", "Menu")
                        .WithMany("MenuYetkis")
                        .HasForeignKey("MenuId")
                        .HasConstraintName("FK_MenuYetki_Menu");

                    b.HasOne("IyilikCatisi.Model.Entity.Roller", "Rol")
                        .WithMany("MenuYetkis")
                        .HasForeignKey("RolId")
                        .HasConstraintName("FK_MenuYetki_Roller");

                    b.Navigation("Menu");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.Mesajlar", b =>
                {
                    b.HasOne("IyilikCatisi.Model.Entity.Kullanicilar", "Kullanici")
                        .WithMany("Mesajlars")
                        .HasForeignKey("KullaniciId")
                        .IsRequired()
                        .HasConstraintName("FK_Mesajlar_Kullanicilar");

                    b.HasOne("IyilikCatisi.Model.Entity.MesajTip", "MesajTip")
                        .WithMany("Mesajlars")
                        .HasForeignKey("MesajTipId")
                        .IsRequired()
                        .HasConstraintName("FK_Mesajlar_MesajTip");

                    b.Navigation("Kullanici");

                    b.Navigation("MesajTip");
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.UyelikAidatlari", b =>
                {
                    b.HasOne("IyilikCatisi.Model.Entity.Kullanicilar", "Kullanici")
                        .WithMany("UyelikAidatlaris")
                        .HasForeignKey("KullaniciId")
                        .HasConstraintName("FK_UyelikAidatlari_Kullanicilar");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.YetkiRol", b =>
                {
                    b.HasOne("IyilikCatisi.Model.Entity.Roller", "Rol")
                        .WithMany("YetkiRols")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK_YetkiRol_Roller");

                    b.HasOne("IyilikCatisi.Model.Entity.Yetkiler", "Yetki")
                        .WithMany("YetkiRols")
                        .HasForeignKey("YetkiId")
                        .IsRequired()
                        .HasConstraintName("FK_YetkiRol_Yetkiler");

                    b.Navigation("Rol");

                    b.Navigation("Yetki");
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.Yorumlar", b =>
                {
                    b.HasOne("IyilikCatisi.Model.Entity.Kullanicilar", "Kullanici")
                        .WithMany("Yorumlars")
                        .HasForeignKey("KullaniciId")
                        .IsRequired()
                        .HasConstraintName("FK_Yorumlar_Kullanicilar");

                    b.HasOne("IyilikCatisi.Model.Entity.YorumTip", "YorumTip")
                        .WithMany("Yorumlars")
                        .HasForeignKey("YorumTipId")
                        .IsRequired()
                        .HasConstraintName("FK_Yorumlar_YorumTip");

                    b.Navigation("Kullanici");

                    b.Navigation("YorumTip");
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.Bildirimler", b =>
                {
                    b.Navigation("BildirimKullanicis");
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.Etkinlik", b =>
                {
                    b.Navigation("EtkinlikFotograflari");
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.Kullanicilar", b =>
                {
                    b.Navigation("Bagislars");

                    b.Navigation("BildirimKullanicis");

                    b.Navigation("Bildirimlers");

                    b.Navigation("Etkinliks");

                    b.Navigation("Haberlers");

                    b.Navigation("KullaniciRols");

                    b.Navigation("Makalelers");

                    b.Navigation("Mesajlars");

                    b.Navigation("UyelikAidatlaris");

                    b.Navigation("Yorumlars");
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.Menu", b =>
                {
                    b.Navigation("InverseUstMenu");

                    b.Navigation("MenuYetkis");
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.MesajTip", b =>
                {
                    b.Navigation("Mesajlars");
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.Roller", b =>
                {
                    b.Navigation("KullaniciRols");

                    b.Navigation("MenuYetkis");

                    b.Navigation("YetkiRols");
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.UyelikDurumu", b =>
                {
                    b.Navigation("Kullanicilars");
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.Yetkiler", b =>
                {
                    b.Navigation("YetkiRols");
                });

            modelBuilder.Entity("IyilikCatisi.Model.Entity.YorumTip", b =>
                {
                    b.Navigation("Yorumlars");
                });
#pragma warning restore 612, 618
        }
    }
}
